spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_mobile
    username: root
    password: B300102
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

jwt:
  secretKey: ite@123!456
  expiration: 86400000